# This is a basic workflow that is manually triggered

name: Package application

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
      - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  package-windows:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Package application
        run: yarn package
        
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: packaged-app
          path: out/
