# This is a basic workflow that is manually triggered

name: Package application

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: 
      - master

jobs:
  build-windows:
    runs-on: windows-2019
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Package application
        run: yarn package
        
        
  upload-artifact:
    runs-on: windows-2019
    needs: [build-windows]
    steps:
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: packaged-app
          path: out/
